baseURL = "https://sofiakodar.github.io/"
title = "sofiakodar.github.io"

theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

[params.author]
  name = "Sofia"
  
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10